# Generated by Django 5.0.1 on 2024-02-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTableView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('view_text', models.TextField(blank=True, default='', help_text='View data: JSON object representation for a view data.', verbose_name='view text')),
                ('context', models.CharField(blank=True, default='', max_length=150, verbose_name='view context')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='table_type')),
            ],
            options={
                'verbose_name': 'base table view',
                'verbose_name_plural': 'base table views',
            },
        ),
        migrations.CreateModel(
            name='ContextViewParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('context', models.CharField(blank=True, default='', max_length=150, verbose_name='view context')),
                ('view_params', models.TextField(blank=True, default='', help_text='View params data: JSON object representation for a view params.', verbose_name='view params')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='table_type')),
            ],
            options={
                'verbose_name': 'context view params',
                'verbose_name_plural': 'context view params',
            },
        ),
        migrations.CreateModel(
            name='NamedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='view name')),
                ('view_text', models.TextField(blank=True, default='', help_text='View data: JSON object representation for a view data.', verbose_name='view text')),
                ('context', models.CharField(blank=True, default='', max_length=250, verbose_name='context')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='table_type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'named filter',
                'verbose_name_plural': 'named filters',
                'unique_together': {('table_type', 'context', 'name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NamedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='view name')),
                ('view_text', models.TextField(blank=True, default='', help_text='View data: JSON object representation for a view data.', verbose_name='view text')),
                ('context', models.CharField(blank=True, default='', max_length=150, verbose_name='view context')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='table_type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'named view',
                'verbose_name_plural': 'named views',
                'unique_together': {('table_type', 'context', 'name', 'user')},
            },
        ),
    ]
