#exclude: ^(migrations/.*|scripts/.*)$
exclude: ^(migrations/.*)$

repos:

- repo: local

  hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [ python ]
      require_serial: true

    - id: ruff-format
      name: ruff-format
      entry: ruff
      language: system
      types: [ python ]
      require_serial: true

    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [ python ]
      require_serial: true

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      require_serial: true
